//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFrontLab.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weapon
    {
        public int WeaponID { get; set; }
        public string WeaponName { get; set; }
        public string Description { get; set; }
        public int ArchetypeID { get; set; }
        public int ElementID { get; set; }
        public int RarityID { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public string Image { get; set; }
        public int InStockID { get; set; }
    
        public virtual Archetype Archetype { get; set; }
        public virtual Element Element { get; set; }
        public virtual InStockStatus InStockStatus { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Rarity Rarity { get; set; }
    }
}
